export const INIT_ACCOUNT = 'INIT_ACCOUNT';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const IMPORT_ACCOUNT = 'IMPORT_ACCOUNT';
export const IMPORT_ACCOUNT_SUCCESS = 'IMPORT_ACCOUNT_SUCCESS';
export const IMPORT_ACCOUNT_ERROR = 'IMPORT_ACCOUNT_ERROR';

export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';

export const LOGOUT = 'LOGOUT';